(function (global) {
  'use strict';
  var instances = new WeakMap();
  function obj(v){return v&&typeof v==='object'&&Object.prototype.toString.call(v)==='[object Object]'?v:{}}
  function arr(v){return Array.isArray(v)?v:[]}
  function txt(v,f){var s=String(v==null?'':v).trim();return s||(f||'')}
  function num(v,f){var n=Number(v);return Number.isFinite(n)?n:(Number.isFinite(f)?f:0)}
  function clone(v,f){try{return JSON.parse(JSON.stringify(v))}catch(e){return f}}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
  function money(v){return num(v,0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}
  function ints(v){return num(v,0).toLocaleString('zh-CN',{maximumFractionDigits:0})}
  function pct(v){return (num(v,0)*100).toLocaleString('zh-CN',{maximumFractionDigits:2})+'%'}
  function firstText(s,keys,f){for(var i=0;i<keys.length;i+=1){var t=txt(s&&s[keys[i]],'');if(t)return t}return f||''}
  function firstNum(s,keys,f){for(var i=0;i<keys.length;i+=1){var n=Number(s&&s[keys[i]]);if(Number.isFinite(n))return n}return Number.isFinite(f)?f:0}
  function call(fn,args){if(typeof fn!=='function')return;try{return fn.apply(null,args||[])}catch(e){console.warn('[G281RecoveryCenter] action failed:',e)}}
  function node(c){if(!c)return null;if(typeof c==='string')return document.querySelector(c);if(c.nodeType===1)return c;return null}
  function actions(o){var s=obj(o);return obj(s.actions&&typeof s.actions==='object'?s.actions:s)}
  function ctx(v){var s=obj(v);var type=firstText(s,['quoteType','type','mode'],'project');return{quoteType:type,quoteTypeLabel:type==='change'?'变更报价':'项目报价',baselineQuoteVersion:firstText(s,['baselineQuoteVersion','baselineVersion','baseQuoteVersion'],''),scenarioName:firstText(s,['scenarioName','quoteName','name'],'当前场景'),quoteVersion:firstText(s,['quoteVersion','version','versionTag'],''),owner:firstText(s,['owner','salesOwner'],'')}}
  function harnessRows(rows){return arr(rows).map(function (r,i){var s=obj(r);var active=arr(s.activeRules);var temp=arr(s.templateReservedRules).concat(arr(s.templateRules));var per=firstNum(s,['projectedRecoveryPerSet','recoveryPerSet'],active.reduce(function(sum,rule){return sum+num(rule&&(rule.perSetRecoverAmount||rule.singleUnitFee),0)},0));var limit=active.reduce(function(m,rule){return Math.max(m,num(rule&&rule.recoverLimitSets,0))},0);var target=active.reduce(function(sum,rule){var total=num(rule&&rule.totalAmount,NaN);if(Number.isFinite(total)&&total>0)return sum+total;return sum+per*Math.max(0,num(rule&&rule.recoverLimitSets,0))},0);var id=firstText(s,['harnessId','harnessNo','harnessCode','no','partNo'],'harness-'+(i+1));return{harnessId:id,harnessNo:firstText(s,['harnessNo','harnessCode','partNo'],id),harnessName:firstText(s,['harnessName','name','partName'],''),grossProfit:firstNum(s,['grossProfit','profit','marginAmount'],0),estimatedRecoveryAmount:firstNum(s,['estimatedRecoveryAmount'],0),projectedRecoveryPerSet:per,recoveryLimitSets:limit,targetAmount:target,effectiveRuleCount:firstNum(s,['effectiveRuleCount'],active.length),templateRuleCount:firstNum(s,['templateRuleCount'],temp.length)}}).filter(function(r){return !!r.harnessId})}
  function trackDraft(row,sets){var delivered=Math.max(0,num(sets,0));var limit=Math.max(0,num(row&&row.recoveryLimitSets,0));var effective=limit>0?Math.min(delivered,limit):delivered;var recovered=Math.max(0,num(row&&row.projectedRecoveryPerSet,0)*effective);var target=Math.max(0,num(row&&row.targetAmount,0));return{harnessId:txt(row&&row.harnessId,''),harnessName:txt(row&&row.harnessName,''),deliveredSets:delivered,recoveredAmount:recovered,remainingAmount:target>0?Math.max(0,target-recovered):0}}
  function trackingRows(raw,hRows){var map=new Map();hRows.forEach(function(r){var d=trackDraft(r,0);map.set(r.harnessId,{harnessId:r.harnessId,harnessNo:r.harnessNo||r.harnessId,harnessName:r.harnessName||'',deliveredSets:d.deliveredSets,recoveredAmount:d.recoveredAmount,remainingAmount:d.remainingAmount,projectedRecoveryPerSet:num(r.projectedRecoveryPerSet,0),recoveryLimitSets:num(r.recoveryLimitSets,0),targetAmount:num(r.targetAmount,0),estimatedRecoveryAmount:num(r.estimatedRecoveryAmount,0),effectiveRuleCount:num(r.effectiveRuleCount,0),templateRuleCount:num(r.templateRuleCount,0)})});arr(raw).forEach(function(item){var id=firstText(item,['harnessId','lineId','harnessNo'],'');if(!id)return;var base=map.get(id)||{harnessId:id,harnessNo:id,harnessName:firstText(item,['harnessName','lineName','name'],''),projectedRecoveryPerSet:0,recoveryLimitSets:0,targetAmount:0,estimatedRecoveryAmount:0,effectiveRuleCount:0,templateRuleCount:0};var d=trackDraft(base,firstNum(item,['deliveredSets','deliveredUnits','shippedSets'],base.deliveredSets));map.set(id,{harnessId:id,harnessNo:base.harnessNo||id,harnessName:base.harnessName,deliveredSets:d.deliveredSets,recoveredAmount:firstNum(item,['recoveredAmount'],d.recoveredAmount),remainingAmount:firstNum(item,['remainingAmount'],d.remainingAmount),projectedRecoveryPerSet:base.projectedRecoveryPerSet,recoveryLimitSets:base.recoveryLimitSets,targetAmount:base.targetAmount,estimatedRecoveryAmount:base.estimatedRecoveryAmount,effectiveRuleCount:base.effectiveRuleCount,templateRuleCount:base.templateRuleCount})});return Array.from(map.values())}
  function recovery(raw,hRows,rawTracking){var s=obj(raw);var rows=trackingRows(rawTracking||s.recoveryTracking||s.shipments||s.deliveryRows,hRows);var delivered=rows.reduce(function(sum,r){return sum+Math.max(0,num(r.deliveredSets,0))},0);var recovered=rows.reduce(function(sum,r){return sum+Math.max(0,num(r.recoveredAmount,0))},0);var targetAmt=rows.reduce(function(sum,r){return sum+Math.max(0,num(r.targetAmount,0))},0);var targetSets=firstNum(s,['targetSets','recoveryCapSets','capSets','upperLimitSets'],0)||rows.reduce(function(m,r){return Math.max(m,Math.max(0,num(r.recoveryLimitSets,0)))},0);var progress=targetAmt>0?recovered/targetAmt:(targetSets>0?delivered/targetSets:0);var thresholds=arr(s.thresholds).map(function(t,i){var q=obj(t);var current=firstNum(q,['current','currentValue'],delivered);var target=firstNum(q,['target','limit','value'],targetSets);return{id:firstText(q,['id','key'],'threshold-'+(i+1)),name:firstText(q,['name','label','title'],'阈值-'+(i+1)),current:current,target:target,reached:q.reached===true||(target>0&&current>=target),note:firstText(q,['note','description','hint'],'')}});if(!thresholds.length&&targetSets>0){thresholds.push({id:'shipment-cap',name:'出货回收窗口',current:delivered,target:targetSets,reached:delivered>=targetSets,note:'按销售维护的回收上限套数跟踪。'})}return{targetSets:targetSets,shippedSets:delivered,recoveredAmount:recovered,targetAmount:targetAmt,progress:progress,thresholds:thresholds,effectiveRuleCount:hRows.reduce(function(sum,r){return sum+Math.max(0,num(r.effectiveRuleCount,0))},0),templateRuleCount:hRows.reduce(function(sum,r){return sum+Math.max(0,num(r.templateRuleCount,0))},0),missing:arr(s.missing).concat(arr(s.missingFields)).filter(Boolean),trackingRows:rows,tasks:arr(s.tasks),harnessRows:hRows}}
  function alerts(raw,rec,c){var list=arr(raw).map(function(a,i){var s=obj(a);return{id:firstText(s,['id','key'],'alert-'+(i+1)),level:firstText(s,['level','severity','type'],'info'),title:firstText(s,['title','name'],'提醒'),message:firstText(s,['message','desc','description'],'')}});if(c.quoteType==='change'&&!c.baselineQuoteVersion)list.push({id:'baseline-missing',level:'warn',title:'缺少基线报价版本',message:'变更报价必须绑定基线版本。'});if(rec.targetSets>0&&rec.shippedSets>=rec.targetSets)list.push({id:'shipment-threshold-reached',level:'warn',title:'已达到回收套数阈值',message:'请按协议规则触发开票或调价复核。'});else if(rec.targetSets>0&&rec.shippedSets/rec.targetSets>=0.8)list.push({id:'shipment-threshold-near',level:'info',title:'接近回收套数阈值',message:'出货已超过阈值的 80%。'});if(rec.missing.length)list.push({id:'rule-fields-missing',level:'warn',title:'销售规则字段未补齐',message:'待补字段：'+rec.missing.join('、')});if(rec.effectiveRuleCount<=0)list.push({id:'effective-rule-empty',level:'warn',title:'当前没有有效回收规则',message:'零金额模板行只保留结构，不参与当前回收。'});return list}
  function task(raw,i){var s=obj(raw);return{id:firstText(s,['id','taskId'],'task-'+(i+1)),title:firstText(s,['title','name'],'待办事项'),owner:firstText(s,['owner','assignee','role'],'项目经理'),due:firstText(s,['due','dueDate','deadline'],'本周'),status:firstText(s,['status','state'],'待处理'),note:firstText(s,['note','description','message'],''),updatedAt:firstText(s,['updatedAt'],'')}}
  function derivedTasks(rec,als){var list=[{id:'shipment-update',title:'更新实际出货',owner:'业务/销售',due:'每周',status:rec.shippedSets>0?'进行中':'待开始',note:'按承载线束号回填出货套数。'}];if(als.some(function(a){return a.id==='rule-fields-missing'}))list.push({id:'rule-complete',title:'补齐销售规则字段',owner:'销售',due:'本周',status:'待处理',note:'补齐字段后再做正式判断。'});if(als.some(function(a){return a.id==='baseline-missing'}))list.push({id:'baseline-bind',title:'绑定变更报价基线',owner:'销售/项目经理',due:'尽快',status:'待处理',note:'变更报价必须挂在基线版本上。'});if(als.some(function(a){return a.id==='shipment-threshold-reached'}))list.push({id:'invoice-reprice',title:'触发开票/调价复核',owner:'销售/财务/项目经理',due:'立即',status:'待确认',note:'出货已达到协议阈值。'});return list}
  function mergedTasks(raw,rec,als){var map=new Map();derivedTasks(rec,als).forEach(function(t,i){var n=task(t,i);map.set(n.id,n)});arr(raw).forEach(function(t,i){var n=task(t,i);map.set(n.id,n)});return Array.from(map.values())}
  function view(payload,options){var source=obj(payload);var c=ctx(source.quoteContext);var hRows=harnessRows(source.harnessRows);var rec=recovery(source.recovery,hRows,source.recoveryTracking);var als=alerts(source.alerts,rec,c);return{payload:clone(source,{}),quoteContext:c,recovery:rec,alerts:als,tasks:mergedTasks(source.tasks||rec.tasks,rec,als),topHarnessRows:hRows.slice().sort(function(l,r){return num(r.estimatedRecoveryAmount,0)-num(l.estimatedRecoveryAmount,0)}).slice(0,6),actions:actions(options)}}
  function levelClass(v){var s=txt(v,'info').toLowerCase();if(s==='warn'||s==='warning'||s==='error')return'negative';if(s==='success'||s==='ok')return'positive';return''}
  function ruleText(rec){var parts=['有效规则 '+ints(rec.effectiveRuleCount)+' 条','模板保留行 '+ints(rec.templateRuleCount)+' 条'];if(rec.missing.length)parts.push('待补字段 '+ints(rec.missing.length)+' 项');return parts.join(' / ')}
  function section(title,body,note){return'<section class="card mt"><h3>'+title+'</h3>'+(note?'<p class="section-note">'+note+'</p>':'')+body+'</section>'}
  function summaryHtml(v){var rec=v.recovery;var remaining=Math.max(0,num(rec.targetAmount,0)-num(rec.recoveredAmount,0));return'<div class="ledger"><article class="ledger-item"><div><strong>出货进度</strong><div class="subtle">目标套数：'+ints(rec.targetSets)+' 套</div></div><div class="meta">'+ints(rec.shippedSets)+' 套 / '+pct(rec.progress)+'</div></article><article class="ledger-item"><div><strong>已回收金额</strong><div class="subtle">按承载线束规则回算</div></div><div class="meta">'+money(rec.recoveredAmount)+'</div></article><article class="ledger-item"><div><strong>待回收金额</strong><div class="subtle">目标金额：'+money(rec.targetAmount)+'</div></div><div class="meta '+(remaining<=0?'positive':'')+'">'+money(remaining)+'</div></article><article class="ledger-item"><div><strong>规则状态</strong><div class="subtle">零金额模板行只保留结构</div></div><div class="meta">'+esc(ruleText(rec))+'</div></article></div>'}
  function alertsHtml(v){if(!v.alerts.length)return'<p class="section-note">当前没有额外提醒。</p>';return'<div class="ledger">'+v.alerts.map(function(a){return'<article class="ledger-item"><div><strong>'+esc(a.title)+'</strong><div class="subtle">'+esc(a.message||'-')+'</div></div><div class="meta '+levelClass(a.level)+'">'+esc(txt(a.level,'info').toUpperCase())+'</div></article>'}).join('')+'</div>'}
  function thresholdHtml(v){if(!v.recovery.thresholds.length)return'<p class="section-note">当前没有可追踪阈值。</p>';return'<div class="table-wrap"><table class="compare-table"><thead><tr><th>阈值项</th><th>当前值</th><th>目标值</th><th>状态</th><th>说明</th></tr></thead><tbody>'+v.recovery.thresholds.map(function(t){return'<tr><td>'+esc(t.name)+'</td><td>'+ints(t.current)+'</td><td>'+ints(t.target)+'</td><td class="'+(t.reached?'positive':'')+'">'+(t.reached?'已触发':'未触发')+'</td><td>'+esc(t.note||'-')+'</td></tr>'}).join('')+'</tbody></table></div>'}
  function tasksHtml(v){return'<div class="toolbar" style="justify-content:flex-end;padding:0 0 8px 0;"><button class="mini-button secondary" type="button" data-rc-add-task>新增任务</button></div><div class="table-wrap"><table class="compare-table"><thead><tr><th>任务</th><th>责任人</th><th>节点</th><th>状态</th><th>说明</th><th>操作</th></tr></thead><tbody>'+v.tasks.map(function(t){return'<tr data-rc-task-id="'+esc(t.id)+'"><td><input class="version-option-input" data-rc-task-field="title" type="text" value="'+esc(t.title)+'" /></td><td><input class="version-option-input" data-rc-task-field="owner" type="text" value="'+esc(t.owner)+'" /></td><td><input class="version-option-input" data-rc-task-field="due" type="text" value="'+esc(t.due)+'" /></td><td><select class="version-option-input" data-rc-task-field="status">'+['待处理','待开始','进行中','待确认','已完成'].map(function(s){return'<option value="'+esc(s)+'"'+(t.status===s?' selected':'')+'>'+esc(s)+'</option>'}).join('')+'</select></td><td><input class="version-option-input" data-rc-task-field="note" type="text" value="'+esc(t.note)+'" /></td><td><button class="mini-button" type="button" data-rc-remove-task="'+esc(t.id)+'">删除</button></td></tr>'}).join('')+'</tbody></table></div>'}
  function trackingHtml(v){if(!v.recovery.trackingRows.length)return'<p class="section-note">当前没有可编辑的承载线束出货记录。</p>';return'<div class="table-wrap"><table class="compare-table"><thead><tr><th>线束号</th><th>线束名称</th><th>有效规则</th><th>模板行</th><th>出货套数</th><th>已回收</th><th>待回收</th></tr></thead><tbody>'+v.recovery.trackingRows.map(function(r){return'<tr data-rc-harness-id="'+esc(r.harnessId)+'" data-rc-harness-name="'+esc(r.harnessName||'')+'"><td>'+esc(r.harnessNo||r.harnessId)+'</td><td>'+esc(r.harnessName||'-')+'</td><td>'+ints(r.effectiveRuleCount)+'</td><td>'+ints(r.templateRuleCount)+'</td><td><input class="version-option-input" type="number" min="0" step="1" data-rc-shipment-input value="'+esc(r.deliveredSets)+'" /></td><td>'+money(r.recoveredAmount)+'</td><td>'+money(r.remainingAmount)+'</td></tr>'}).join('')+'</tbody></table></div>'}
  function focusHtml(v){if(!v.topHarnessRows.length)return'<p class="section-note">当前没有可聚焦的承载线束数据。</p>';return'<div class="table-wrap"><table class="compare-table"><thead><tr><th>线束号</th><th>线束名称</th><th>预计回收金额</th><th>基础毛利/套</th><th>有效规则</th></tr></thead><tbody>'+v.topHarnessRows.map(function(r){return'<tr><td>'+esc(r.harnessNo||r.harnessId)+'</td><td>'+esc(r.harnessName||'-')+'</td><td>'+money(r.estimatedRecoveryAmount)+'</td><td class="'+(num(r.grossProfit,0)>=0?'positive':'negative')+'">'+money(r.grossProfit)+'</td><td>'+ints(r.effectiveRuleCount)+'</td></tr>'}).join('')+'</tbody></table></div>'}
  function html(v){var c=v.quoteContext;var chips='<div class="hero-badges"><span class="chip"><span class="dot"></span><span>报价类型：'+esc(c.quoteTypeLabel)+'</span></span><span class="chip"><span class="dot alt"></span><span>基线版本：'+esc(c.baselineQuoteVersion||'未填写')+'</span></span><span class="chip"><span class="dot gold"></span><span>场景：'+esc(c.scenarioName)+'</span></span>'+(c.quoteVersion?'<span class="chip"><span>报价版本：'+esc(c.quoteVersion)+'</span></span>':'')+(c.owner?'<span class="chip"><span>责任销售：'+esc(c.owner)+'</span></span>':'')+'</div>';return'<section class="card"><h3>回收中心</h3><p class="section-note">按销售回收规则和实际出货，跟踪回收、任务触发和线束颗粒度执行结果。</p>'+chips+'</section>'+section('回收进度摘要',summaryHtml(v))+section('线束出货跟踪',trackingHtml(v),'由业务定期回填承载线束出货，系统按当前规则回算已回收与剩余金额。')+section('阈值与触发',thresholdHtml(v))+section('触发提醒',alertsHtml(v))+section('待跟踪任务',tasksHtml(v))+section('承载线束焦点',focusHtml(v))}
  function getInstance(container){var el=node(container);if(!el)return null;var inst=instances.get(el);if(inst)return inst;inst={container:el,payload:{},options:{},view:null,handlers:null};instances.set(el,inst);return inst}
  function draw(inst,payload){inst.payload=clone(payload,{});inst.view=view(inst.payload,inst.options);inst.container.innerHTML=html(inst.view);inst.container.dataset.recoveryCenterMounted='true';inst.container.dataset.recoveryCenterAt=new Date().toISOString()}
  function findTask(v,id){return arr(v&&v.tasks).find(function(t){return t.id===id})||null}
  function findTracking(v,id){return arr(v&&v.recovery&&v.recovery.trackingRows).find(function(r){return r.harnessId===id})||null}
  function bind(inst){if(!inst||inst.handlers)return;var onClick=function(e){var t=e.target;if(!t)return;var add=t.closest('[data-rc-add-task]');if(add){var draft={id:'task-'+Date.now().toString(36),title:'新回收任务',owner:'项目经理',due:'本周',status:'待处理',note:''};if(typeof inst.view.actions.onTaskAdd==='function')call(inst.view.actions.onTaskAdd,[clone(draft,{})]);else{var next=clone(inst.payload,{});next.tasks=arr(next.tasks).concat([draft]);draw(inst,next)}return}var remove=t.closest('[data-rc-remove-task]');if(remove){var id=txt(remove.getAttribute('data-rc-remove-task'),'');if(!id)return;if(typeof inst.view.actions.onTaskRemove==='function')call(inst.view.actions.onTaskRemove,[id]);else{var payload=clone(inst.payload,{});payload.tasks=arr(payload.tasks).filter(function(item){return txt(item&&item.id,'')!==id});draw(inst,payload)}}};var onChange=function(e){var t=e.target;if(!t)return;var taskField=t.closest('[data-rc-task-field]');if(taskField){var row=t.closest('[data-rc-task-id]');var id=txt(row&&row.getAttribute('data-rc-task-id'),'');var cur=findTask(inst.view,id);if(!cur)return;var nextTask=clone(cur,{});nextTask[taskField.getAttribute('data-rc-task-field')]=txt(taskField.value,'');nextTask.updatedAt=new Date().toISOString();if(typeof inst.view.actions.onTaskChange==='function')call(inst.view.actions.onTaskChange,[clone(nextTask,{}),clone(inst.view,{})]);else{var payload=clone(inst.payload,{});var items=arr(payload.tasks).slice();var idx=items.findIndex(function(item){return txt(item&&item.id,'')===id});if(idx>=0)items[idx]=nextTask;else items.push(nextTask);payload.tasks=items;draw(inst,payload)}return}var shipment=t.closest('[data-rc-shipment-input]');if(shipment){var shipmentRow=t.closest('[data-rc-harness-id]');var hid=txt(shipmentRow&&shipmentRow.getAttribute('data-rc-harness-id'),'');var curRow=findTracking(inst.view,hid);if(!curRow)return;var record=trackDraft(curRow,shipment.value);record.harnessId=hid;record.harnessName=txt(shipmentRow&&shipmentRow.getAttribute('data-rc-harness-name'),curRow.harnessName);record.updatedAt=new Date().toISOString();if(typeof inst.view.actions.onShipmentChange==='function')call(inst.view.actions.onShipmentChange,[clone(record,{}),clone(inst.view,{})]);else{var nextPayload=clone(inst.payload,{});var recs=arr(nextPayload.recoveryTracking).slice();var idx2=recs.findIndex(function(item){return txt(item&&(item.harnessId||item.lineId),'')===hid});if(idx2>=0)recs[idx2]=record;else recs.push(record);nextPayload.recoveryTracking=recs;draw(inst,nextPayload)}}};inst.container.addEventListener('click',onClick);inst.container.addEventListener('change',onChange);inst.handlers={onClick:onClick,onChange:onChange}}
  function unbind(inst){if(!inst||!inst.handlers)return;inst.container.removeEventListener('click',inst.handlers.onClick);inst.container.removeEventListener('change',inst.handlers.onChange);inst.handlers=null}
  function render(container,payload,options){var inst=getInstance(container);if(!inst)return false;inst.options=obj(options);draw(inst,payload);bind(inst);return true}
  function mount(container,payload,options){return render(container,payload,options)}
  function unmount(container){var inst=getInstance(container);if(!inst)return false;unbind(inst);inst.container.innerHTML='';delete inst.container.dataset.recoveryCenterMounted;delete inst.container.dataset.recoveryCenterAt;instances.delete(inst.container);return true}
  global.G281RecoveryCenter={mount:mount,render:render,unmount:unmount}
}(window));
